# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

def define_pg_vm(config, n)
  # VM configuration for postgres nodes
  name = "pg0#{n}"
  ip = "192.168.121.10#{n}"
  config.vm.define name do |kconfig|
    kconfig.vm.hostname = "#{name}.vagrant"
    kconfig.vm.provider :libvirt do |domain|
      domain.memory = 1024
      domain.cpus = 2
    end
    kconfig.vm.network "private_network", ip: ip
    yield kconfig if block_given?

    # Enable log-in with interactive user ssh key on all the VMs,
    # TODO: check what to do for e.g. Travis-CI, generate a new key-pair?
    # Note: by default vagrant generates a new key pair for *every* VM,
    # making handling cumbersome.
    ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
    config.vm.provision 'shell', inline: "mkdir -p /root/.ssh"
    config.vm.provision 'shell', inline: "echo #{ssh_pub_key} >> /root/.ssh/authorized_keys"
    config.vm.provision 'shell', inline: "echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys", privileged: false

    kconfig.vm.provision "ansible" do |ansible|
      ansible.playbook = "init-test-servers.yml"
      ansible.inventory_path = "vagrant_servers"
      ansible.verbose = "vv"
      ansible.limit = ip
      ansible.skip_tags = []
      ansible.extra_vars = {remote_user: "root"} # Alternatively: use user "vagrant"
    end
  end
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # config.vm.box = "ubuntu/xenial64"
  config.vm.box = "generic/ubuntu1604"
  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :machine
    config.cache.enable :gem
    config.cache.enable :generic, {
      'install' => { cache_dir: '/var/cache/install' }
    }
  else
    puts "Please run: `vagrant plugin install vagrant-cachier` to enable caching and faster provisioning"
  end

  # config.hostsupdater.remove_on_suspend = false

  #config.vm.synced_folder "..", "/vagrant"
  vagrant_root = File.dirname(__FILE__)
  ENV['ANSIBLE_ROLES_PATH'] = "#{vagrant_root}/../.."

  define_pg_vm config, 2
  define_pg_vm config, 3
  define_pg_vm config, 4
  define_pg_vm config, 1 do |kconfig|
    kconfig.vm.network "forwarded_port", guest: 5432, host: 15432
  end
end
