---
- name: Configuration to run once, not per DB instance
  hosts: localhost
  gather_facts: False
  vars:
    credentials_store: /tmp # please provide some folder and store it's content in a secure place
    aws_account: None # `dev` or `prod` because we use different aws accounts for development and prod
  tasks:
    - debug: var=aws_account
    - fail:
        msg: 'Please provide --extra-vars "aws_account=..." Use e.g. `dev` or `prod`'
      when: aws_account is undefined

    - name: Create user for creating backup buckets
      iam:
        iam_type: user
        name: backup_configurer
        state: present
        access_key_state: create
      register: backup_configurer

    - name: Define policy for creating backup buckets
      iam_policy:
        iam_type: user
        iam_name: backup_configurer
        policy_name: backup_configurer_policy
        state: present
        policy_json: |
          {
              "Version": "2012-10-17",
              "Statement": [
                  {
                      "Sid": "Stmt1489412511000",
                      "Effect": "Allow",
                      "Action": [
                          "s3:CreateBucket",
                          "s3:GetBucket*",
                          "s3:GetBucketLocation",
                          "s3:GetBucketPolicy",
                          "s3:CreateBucket",
                          "s3:ListBucket",
                          "s3:ListAllMyBuckets",
                          "s3:PutBucketPolicy",
                          "s3:*"
                      ],
                      "Resource": [
                          "arn:aws:s3:::*"
                      ]
                  },
                  {
                      "Sid": "Stmt1489412511000a",
                      "Effect": "Allow",
                      "Action": [
                        "iam:GetUser",
                        "iam:CreateUser",
                        "iam:CreateAccessKey",
                        "iam:ListAccessKeys",
                        "iam:ListGroups",
                        "iam:ListRoles",
                        "iam:ListInstanceProfiles",
                        "iam:ListUsers"
                      ],
                      "Resource": [
                        "arn:aws:iam::*"
                      ]
                  }
              ]
          }

    - name: Create target directory
      file:
        state: directory
        mode: 0755
        path: "{{ credentials_store }}/backup/{{ aws_account }}"

    - name: Create AWS access file
      template:
        src: "backup_configurer.credentials.sh.j2"
        dest: "{{ credentials_store }}/backup/{{ aws_account }}/configurer.credentials.sh"
      when: backup_configurer.changed
      register: credentials_sh_file

    - name: Create AWS access file
      template:
        src: "backup_configurer.credentials.properties.j2"
        dest: "{{ credentials_store }}/backup/{{ aws_account }}/configurer.credentials.properties"
      when: backup_configurer.changed
      register: credentials_properties_file

    - debug:
        msg: |
          AWS credentials file created in
          {{ credentials_sh_file.dest }} and
          {{ credentials_properties_file.dest }}
          Please keep secure, do not check in, keep available for creating db instances.
      when: backup_configurer.changed


