# For documentation and example see
# http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html
AWSTemplateFormatVersion: "2010-09-09"
Resources:
  BackupConfigurer:
    Type: "AWS::IAM::User"
    Properties:
      UserName: backup_configurer

#~  BackupConfigurerRole:
#~    Type: "AWS::IAM::Role"
#~    Properties:
#~      AssumeRolePolicyDocument:
#~        Version: "2012-10-17"
#~        Statement:
#~          -
#~            Effect: "Allow"
#~            Principal:
#~              Service:
#~                - "ec2.amazonaws.com"
#~            Action:
#~              - "sts:AssumeRole"
#~      Path: "/"
#~      Policies:
#~        -
#~          PolicyName: "root"
#~          PolicyDocument:
#~            Version: "2012-10-17"
#~            Statement:
#~              -
#~                Effect: "Allow"
#~                Action: "*"
#~                Resource: "*"
#~  RootInstanceProfile:
#~    Type: "AWS::IAM::InstanceProfile"
#~    Properties:
#~      Path: "/"
#~      Roles:
#~        -
#~          Ref: "RootRole"
