# Decide: reuse through import-playbook or (fine granular) by referring to single task-lists

tasks:
  generate-or-load-postgres-credentials

include_role:
  tasks_from: init_settings.yaml
include_role:
  tasks_from: build_groups.yaml
include_role:
  tasks_from: deactivate_servers.yaml
# prepare admin-, replicator- passwords
include_role:
  tasks_from: setup_master.yaml
include_role:
  tasks_from: register_master_in_dns # highly specific
include_role:
  tasks_from: create_postgres_users
include_role:
  tasks_from: setup_slaves
include_role:
  tasks_from: register_slaves_as_readonly # new, for BSNA

hosts: aws_commands_host
include_role:
  tasks_from: setup_offsite_backup # specific
